/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Администратор
 */
import java.net.URL;
import java.io.IOException;

public class LiveMDIApplication extends javax.swing.JFrame {

    /**
     * Creates new form LiveMDIApplication
     */
    public LiveMDIApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        exerButton = new javax.swing.JButton();
        videoButton = new javax.swing.JButton();
        bookButton2 = new javax.swing.JButton();
        audioButton = new javax.swing.JButton();
        appButton = new javax.swing.JButton();
        lessButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        desktopPane.setMinimumSize(new java.awt.Dimension(1024, 768));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1024, 768));

        exerButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        exerButton.setText("Упражнения");
        exerButton.setPreferredSize(new java.awt.Dimension(150, 150));
        exerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exerButtonActionPerformed(evt);
            }
        });
        exerButton.setBounds(50, 470, 230, 160);
        jLayeredPane1.add(exerButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        videoButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        videoButton.setText("Видеоматериалы");
        videoButton.setPreferredSize(new java.awt.Dimension(150, 150));
        videoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoButtonActionPerformed(evt);
            }
        });
        videoButton.setBounds(710, 470, 230, 160);
        jLayeredPane1.add(videoButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bookButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bookButton2.setText("Тексты");
        bookButton2.setPreferredSize(new java.awt.Dimension(150, 150));
        bookButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButton2ActionPerformed(evt);
            }
        });
        bookButton2.setBounds(50, 260, 230, 160);
        jLayeredPane1.add(bookButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        audioButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        audioButton.setText("Аудиоматериалы");
        audioButton.setPreferredSize(new java.awt.Dimension(150, 150));
        audioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioButtonActionPerformed(evt);
            }
        });
        audioButton.setBounds(710, 50, 230, 160);
        jLayeredPane1.add(audioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        appButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        appButton.setText("Приложения");
        appButton.setPreferredSize(new java.awt.Dimension(150, 150));
        appButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appButtonActionPerformed(evt);
            }
        });
        appButton.setBounds(710, 260, 230, 160);
        jLayeredPane1.add(appButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lessButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lessButton.setText("Уроки");
        lessButton.setPreferredSize(new java.awt.Dimension(150, 150));
        lessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessButtonActionPerformed(evt);
            }
        });
        lessButton.setBounds(50, 50, 230, 160);
        jLayeredPane1.add(lessButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LiveBack_1024_LS.jpg"))); // NOI18N
        jLabel2.setLabelFor(jTabbedPane1);
        jLabel2.setBounds(0, 0, 1020, 740);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Главная", jLayeredPane1);

        jTabbedPane1.setBounds(0, 0, 1024, 768);
        desktopPane.add(jTabbedPane1, javax.swing.JLayeredPane.DRAG_LAYER);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void lessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessButtonActionPerformed
        // TODO add your handling code here:
        javax.swing.JList lessList = new javax.swing.JList();
        javax.swing.JPanel lessPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane lessListScroll= new javax.swing.JScrollPane();
        javax.swing.JScrollPane lessEditScroll= new javax.swing.JScrollPane();
        javax.swing.JEditorPane lessEditorPane = new javax.swing.JEditorPane();

        lessList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lessList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Lesson_Name 1", "Lesson_Name 2", "Lesson_Name 3", "Lesson_Name 4", "Lesson_Name 5" };
            @Override
            public int getSize() { return strings.length; }
            @Override
            public Object getElementAt(int i) { return strings[i]; }
        });
        
        lessEditorPane.setEditable(false);
        java.net.URL helpURL = LiveMDIApplication.class.getResource(
                                        "Lessons.html");
        if (helpURL != null) {
            try {
                lessEditorPane.setPage(helpURL);
            } catch (IOException e) {
                System.err.println("Attempted to read a bad URL: " + helpURL);
            }
        } else {
            System.err.println("Couldn't find file: TextSamplerDemoHelp.html");
        }
              
        lessListScroll.setViewportView(lessList);
        lessEditScroll.setViewportView(lessEditorPane);
        
        javax.swing.GroupLayout lessLayout = new javax.swing.GroupLayout(lessPanel);
        lessPanel.setLayout(lessLayout);
        lessLayout.setHorizontalGroup(
            lessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lessLayout.createSequentialGroup()
                .addComponent(lessListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lessEditScroll))
        );
        lessLayout.setVerticalGroup(
            lessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lessListScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addComponent(lessEditScroll)
        );    
        
        jTabbedPane1.addTab("Предпросмотр уроков", lessPanel);
        jTabbedPane1.setTabComponentAt(jTabbedPane1.indexOfTab("Предпросмотр уроков"),
                new ButtonTabComponent(jTabbedPane1));
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Предпросмотр уроков"));
    }//GEN-LAST:event_lessButtonActionPerformed

    private void appButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appButtonActionPerformed
         // TODO add your handling code here:
        javax.swing.JList lessList = new javax.swing.JList();
        javax.swing.JPanel lessPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane lessListScroll= new javax.swing.JScrollPane();
        javax.swing.JScrollPane lessTextScroll= new javax.swing.JScrollPane();
        javax.swing.JTable audioTable = new javax.swing.JTable();
        javax.swing.JTextArea appText = new javax.swing.JTextArea();
        javax.swing.JInternalFrame app = new javax.swing.JInternalFrame();

        
        lessList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lessList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Приложение 1", "Программа 2", "Интерактивная игра 3", "Приложение 4", "Приложение 5" };
            @Override
            public int getSize() { return strings.length; }
            @Override
            public Object getElementAt(int i) { return strings[i]; }
        });
        
        app.setVisible(true);
        javax.swing.GroupLayout appLayout = new javax.swing.GroupLayout(app.getContentPane());
        app.getContentPane().setLayout(appLayout);
        appLayout.setHorizontalGroup(
            appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
        );
        appLayout.setVerticalGroup(
            appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        
        appText.setColumns(20);
        appText.setEditable(false);
        appText.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        appText.setRows(5);
        appText.setText("Правила игры. Задание к интерактивному упражнению.");
        
        lessListScroll.setViewportView(lessList);
        lessTextScroll.setViewportView(appText);     
        
        javax.swing.GroupLayout lessLayout = new javax.swing.GroupLayout(lessPanel);
        lessPanel.setLayout(lessLayout);
        lessLayout.setHorizontalGroup(
            lessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lessLayout.createSequentialGroup()
                .addComponent(lessListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(app, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lessTextScroll))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                )
        );
        lessLayout.setVerticalGroup(
            lessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lessListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 740, Short.MAX_VALUE)
            .addGroup(lessLayout.createSequentialGroup()
                .addComponent(app, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lessTextScroll)
                )
        );    
        //lessPanel.add(player);
        jTabbedPane1.addTab("Предпросмотр приложений", lessPanel);
        jTabbedPane1.setTabComponentAt(jTabbedPane1.indexOfTab("Предпросмотр приложений"),
                new ButtonTabComponent(jTabbedPane1));
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Предпросмотр приложений"));
    }//GEN-LAST:event_appButtonActionPerformed

    private void audioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioButtonActionPerformed
        // TODO add your handling code here:
        javax.swing.JList lessList = new javax.swing.JList();
        javax.swing.JPanel lessPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane lessListScroll= new javax.swing.JScrollPane();
        javax.swing.JScrollPane lessTableScroll= new javax.swing.JScrollPane();
        javax.swing.JTable audioTable = new javax.swing.JTable();
        //MPlayer player= new MPlayer();
        javax.swing.JLabel audioPlayer= new javax.swing.JLabel();
        
        lessList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lessList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Lesson_Name 1", "Lesson_Name 2", "Lesson_Name 3", "Lesson_Name 4", "Lesson_Name 5" };
            @Override
            public int getSize() { return strings.length; }
            @Override
            public Object getElementAt(int i) { return strings[i]; }
        });
        
        audioTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        audioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Интервью ", "Краткая справочная информация", "5 мин"},
                {"Из новостей", "Краткая справочная информация", "10 мин"},
                {"Диалог", "Краткая справочная информация", "7 мин"},
                {"Контрольное аудирование 1", "Краткая справочная информация", "5 мин"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Имя", "Информация", "Продолжительность"
            }
        ));
        audioTable.setMinimumSize(new java.awt.Dimension(45, 200));
        audioTable.setPreferredSize(new java.awt.Dimension(225, 768));
        audioTable.setRowHeight(30);

        audioPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/audioPlayer.png"))); // NOI18N
        
        lessListScroll.setViewportView(lessList);
        lessTableScroll.setViewportView(audioTable);      
        
        javax.swing.GroupLayout lessLayout = new javax.swing.GroupLayout(lessPanel);
        lessPanel.setLayout(lessLayout);
        lessLayout.setHorizontalGroup(
            lessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lessLayout.createSequentialGroup()
                .addComponent(lessListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lessTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
                //.addContainerGap(225, Short.MAX_VALUE)
                //.addComponent(player)
                .addComponent(audioPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                )
        );
        lessLayout.setVerticalGroup(
            lessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lessListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 740, Short.MAX_VALUE)
            .addComponent(lessTableScroll)
            //.addComponent(player)
            .addComponent(audioPlayer)
        );    
        //lessPanel.add(player);
        jTabbedPane1.addTab("Предпросмотр аудиоматериалов", lessPanel);
        jTabbedPane1.setTabComponentAt(jTabbedPane1.indexOfTab("Предпросмотр аудиоматериалов"),
                new ButtonTabComponent(jTabbedPane1));
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Предпросмотр аудиоматериалов"));
    }//GEN-LAST:event_audioButtonActionPerformed

    private void bookButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButton2ActionPerformed
                // TODO add your handling code here:
        javax.swing.JList lessList = new javax.swing.JList();
        javax.swing.JPanel lessPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane lessListScroll= new javax.swing.JScrollPane();
        javax.swing.JScrollPane lessEditScroll= new javax.swing.JScrollPane();
        javax.swing.JEditorPane lessEditorPane = new javax.swing.JEditorPane();

        lessList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lessList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Lesson_Name 1", "Lesson_Name 2", "Lesson_Name 3", "Lesson_Name 4", "Lesson_Name 5" };
            @Override
            public int getSize() { return strings.length; }
            @Override
            public Object getElementAt(int i) { return strings[i]; }
        });
        
        lessEditorPane.setEditable(false);
        java.net.URL helpURL = LiveMDIApplication.class.getResource(
                                        "Lessons.html");
        if (helpURL != null) {
            try {
                lessEditorPane.setPage(helpURL);
            } catch (IOException e) {
                System.err.println("Attempted to read a bad URL: " + helpURL);
            }
        } else {
            System.err.println("Couldn't find file: TextSamplerDemoHelp.html");
        }
              
        lessListScroll.setViewportView(lessList);
        lessEditScroll.setViewportView(lessEditorPane);
        
        javax.swing.GroupLayout lessLayout = new javax.swing.GroupLayout(lessPanel);
        lessPanel.setLayout(lessLayout);
        lessLayout.setHorizontalGroup(
            lessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lessLayout.createSequentialGroup()
                .addComponent(lessListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lessEditScroll))
        );
        lessLayout.setVerticalGroup(
            lessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lessListScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addComponent(lessEditScroll)
        );    
        
        jTabbedPane1.addTab("Предпросмотр текстов", lessPanel);
        jTabbedPane1.setTabComponentAt(jTabbedPane1.indexOfTab("Предпросмотр текстов"),
                new ButtonTabComponent(jTabbedPane1));
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Предпросмотр текстов"));
    }//GEN-LAST:event_bookButton2ActionPerformed

    private void videoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoButtonActionPerformed
         // TODO add your handling code here:
        javax.swing.JList lessList = new javax.swing.JList();
        javax.swing.JPanel lessPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane lessListScroll= new javax.swing.JScrollPane();
        javax.swing.JScrollPane lessTableScroll= new javax.swing.JScrollPane();
        javax.swing.JTable audioTable = new javax.swing.JTable();
        //MPlayer player= new MPlayer();
        javax.swing.JLabel audioPlayer= new javax.swing.JLabel();
        
        lessList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lessList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Lesson_Name 1", "Lesson_Name 2", "Lesson_Name 3", "Lesson_Name 4", "Lesson_Name 5" };
            @Override
            public int getSize() { return strings.length; }
            @Override
            public Object getElementAt(int i) { return strings[i]; }
        });
        
        audioTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        audioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Видео урок 1 ", "Краткая справочная информация", "5 мин"},
                {"Из новостей", "Краткая справочная информация", "10 мин"},
                {"Видео урок 2", "Краткая справочная информация", "7 мин"},
                {"Видео урок 3", "Краткая справочная информация", "5 мин"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Имя", "Информация", "Продолжительность"
            }
        ));
        audioTable.setMinimumSize(new java.awt.Dimension(45, 200));
        audioTable.setPreferredSize(new java.awt.Dimension(225, 768));
        audioTable.setRowHeight(30);
        
        audioPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/videoPlayer.png"))); // NOI18N

        lessListScroll.setViewportView(lessList);
        lessTableScroll.setViewportView(audioTable);      
        
        javax.swing.GroupLayout lessLayout = new javax.swing.GroupLayout(lessPanel);
        lessPanel.setLayout(lessLayout);
        lessLayout.setHorizontalGroup(
            lessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lessLayout.createSequentialGroup()
                .addComponent(lessListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lessTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
                //.addContainerGap(225, Short.MAX_VALUE)
                //.addComponent(player)
                .addComponent(audioPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                )
        );
        lessLayout.setVerticalGroup(
            lessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lessListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 740, Short.MAX_VALUE)
            .addComponent(lessTableScroll)
            //.addComponent(player)
            .addComponent(audioPlayer)
        );    
        //lessPanel.add(player);
        jTabbedPane1.addTab("Предпросмотр видеоматериалов", lessPanel);
        jTabbedPane1.setTabComponentAt(jTabbedPane1.indexOfTab("Предпросмотр видеоматериалов"),
                new ButtonTabComponent(jTabbedPane1));
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Предпросмотр видеоматериалов"));
    }//GEN-LAST:event_videoButtonActionPerformed

    private void exerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exerButtonActionPerformed
                // TODO add your handling code here:
        javax.swing.JList lessList = new javax.swing.JList();
        javax.swing.JPanel lessPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane lessListScroll= new javax.swing.JScrollPane();
        javax.swing.JScrollPane lessEditScroll= new javax.swing.JScrollPane();
        javax.swing.JEditorPane lessEditorPane = new javax.swing.JEditorPane();

        lessList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lessList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Lesson_Name 1", "Lesson_Name 2", "Lesson_Name 3", "Lesson_Name 4", "Lesson_Name 5" };
            @Override
            public int getSize() { return strings.length; }
            @Override
            public Object getElementAt(int i) { return strings[i]; }
        });
        
        lessEditorPane.setEditable(false);
        java.net.URL helpURL = LiveMDIApplication.class.getResource(
                                        "Lessons.html");
        if (helpURL != null) {
            try {
                lessEditorPane.setPage(helpURL);
            } catch (IOException e) {
                System.err.println("Attempted to read a bad URL: " + helpURL);
            }
        } else {
            System.err.println("Couldn't find file: TextSamplerDemoHelp.html");
        }
              
        lessListScroll.setViewportView(lessList);
        lessEditScroll.setViewportView(lessEditorPane);
        
        javax.swing.GroupLayout lessLayout = new javax.swing.GroupLayout(lessPanel);
        lessPanel.setLayout(lessLayout);
        lessLayout.setHorizontalGroup(
            lessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lessLayout.createSequentialGroup()
                .addComponent(lessListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lessEditScroll))
        );
        lessLayout.setVerticalGroup(
            lessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lessListScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addComponent(lessEditScroll)
        );    
        
        jTabbedPane1.addTab("Предпросмотр упражнений", lessPanel);
        jTabbedPane1.setTabComponentAt(jTabbedPane1.indexOfTab("Предпросмотр упражнений"),
                new ButtonTabComponent(jTabbedPane1));
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Предпросмотр упражнений"));
    }//GEN-LAST:event_exerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiveMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiveMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiveMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiveMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LiveMDIApplication().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton appButton;
    private javax.swing.JButton audioButton;
    private javax.swing.JButton bookButton2;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JButton exerButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton lessButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton videoButton;
    // End of variables declaration//GEN-END:variables
}
